export const DISCOVER_MOVIES = 'DISCOVER_MOVIES';
export const GET_GENRES = 'GET_GENRES';
export const SEARCH_KEYWORDS = 'SEARCH_KEYWORDS';
export const CLEAR_KEYWORDS = 'CLEAR_KEYWORDS';
export const SEARCH_PEOPLE = 'SEARCH_PEOPLE';
export const CLEAR_PEOPLE = 'CLEAR_PEOPLE';
