export default [
  'MM-DD-YYYY',
  'YYYY-MM-DD',
  'MMMM DD YYYY',
  'MMMM Do YYYY',
  'MMM DD YYYY',
  'MMM Do YYYY',
  'MM DD YYYY',
  'MM Do YYYY',
  'YYYY-DD-MM',
  'DD MM YYYY',
  'Do MM YYYY',
  'DD MMM YYYY',
  'Do MMM YYYY',
  'DD MMMM YYYY',
  'Do MMMM YYYY',
  'MMMM DD YYYY',
  'MMMM Do YYYY',
  'YYYY',
];
